org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#Minecraft and Mappings
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

neo_version=21.1.169
neo_version_range=[21.1.169,)
loader_version_range=[1,)

ponder_version=1.0.46

#NeoForge Properties
create_version=6.0.4-73
create_range=[6.0.4,6.1.0)
flywheel_minecraft_version=1.21.1
flywheel_version=1.0.2
registrate_version=MC1.21-1.3.0+62

# Mod Properties
mod_version=1.1.3
maven_group=com.troller2705.createnumismatics
mod_id=create_numismatics
# The human-readable display name for the mod.
mod_name=Create: Numismatics
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=All Rights Reserved
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.troller2705.createnumismatics
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Troller2705, ThermalCube
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Provides a economy focused around the Create mod