pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = "NeoForged"
            url = uri("https://maven.neoforged.net/releases")
        }
        maven {
            name = "FancyModLoader"
            url = uri("https://maven.neoforged.net/fancymodloader")
        }
        maven {
            name = "NeoForged Fallback"
            url = "https://maven.neoforged.net/releases"
            content {
                includeGroup "net.neoforged.fancymodloader"
            }
        }
    }
}

rootProject.name = 'CreateNumismatics'
